pull_request_rules:
  - name: automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
        strict: smart
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}