on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          release-type: node
          package-name: mock-jwks
